### ISSUE TITLE
Not working with Ubuntu 20.04.4 LTS + gmsh 4.4.1

### ISSUE THREAD

**Issue by chandukec** [Duncan-Hunter/pipemesh#1]
Thanks a lot for this utility, I need to do a CFD simulation of the branched pipeline (modified T joint with the branch pipeline at an angle of 30 degrees instead of 90 degrees (as in the case of traditional T-shaped joint)). After a week's struggle, I found this utility very handy and useful. But, even after following your steps to install this utility, I am unable to use the pipe mesh utility. I wrote a single line of code in the newly created file "pipe_trial.py" as:
`from pipemesh import pipes`
when I tried to run this using the `python3 pipe_trial.py`, it is throwing me an error, which says: 
```
free(): invalid pointer
Aborted (core dumped)
```
Even though I am using the virtual_env.
I tried both ways to install: 
1. Directly using `python3 -m pip install --user pipemesh` 
2. Using the virtual environment `sudo apt-get install python3-venv` and subsequent steps in the README.md document.
Any comment/suggestion would be very helpful, thanks in advance.

**Comment by Duncan-Hunter** [comment]
Hi, thanks for getting in touch - I haven't developed on this for a few years, but good to know it can be used.

I've just tried installing it with gmsh 4.3 and it seemed to work still. Can you confirm that you're on a Linux system, I developed this on Ubuntu so that's what should work best.

**Comment by Duncan-Hunter** [comment]
Ah just seen the title - can you show me your site-packages/pipemesh folder - it should look a bit like this:

![image](https://user-images.githubusercontent.com/35367438/172337013-5f02f346-069b-4589-bdc6-a49eeed07be0.png)

**Comment by Duncan-Hunter** [comment]
Another idea could be to get familiar with the GMSH python API, then use the code I've written to help out, happy to answer any  questions, but obviously it was a while ago, so not as familiar.

**Comment by chandukec** [comment]
Hello Duncan, 
Many thanks for your prompt help and reply. I have attached the screenshot, it looks similar (I guess)?
![pipemesh_screenshot](https://user-images.githubusercontent.com/22544253/172337964-3e5b3ee9-301b-4c83-95af-356d3007bd26.png)

**Comment by Duncan-Hunter** [comment]
Yes that looks fine - and can you paste the contents of pipe_trial.py here - I can't find it

**Comment by chandukec** [comment]
It was a single line code (actually nothing), just to verify and import the pipemesh, which goes as:

`from pipemesh import pipes`

**Comment by Duncan-Hunter** [comment]
Ok - I'll have a look at this later and try to recreate it, I've ran that and had no issues.

Try running:

```python
from pipemesh import pipes, pieces, gmsh
import os
import numpy as np

model = gmsh.model
factory = model.occ
mesh = model.mesh

fname = "junction"  # Can be changed
piece = pieces.TJunction(0.5, 0.3, [1, 0,0], [-2,1, 0], 0.1)

mesh.generate(3)
gmsh.fltk.run()
gmsh.finalize()
```

**Comment by chandukec** [comment]
Thanks a lot, so I should run it as: `python3 trial_v0.py` ?

**Comment by chandukec** [comment]
Actually, using this command `python3 trial_v0.py`, I am getting the same exact error as that  before:
```
free(): invalid pointer
Aborted (core dumped)
```

**Comment by Duncan-Hunter** [comment]
> Hello Duncan, Many thanks for your prompt help and reply. I have attached the screenshot, it looks similar (I guess)? ![pipemesh_screenshot](https://user-images.githubusercontent.com/22544253/172337964-3e5b3ee9-301b-4c83-95af-356d3007bd26.png)

Is your venv in the cloned repo? Can you try starting a fresh venv in a separate folder e.g. 
```
$mkdir ~/venvs
$mkdir ~/venvs/pipemesh_venv
$python3 -m venv ~/venvs/pipemesh_venv
$source ~/venvs/pipemesh_venv/bin/activate
(pipemesh_venv) $python3 -m pip install pipemesh scipy
```
Then place the libgmsh files in the fresh environment (~/venvs/pipemesh_venv/lib/python3.8/site-packages/pipemesh)
Then try running your file
```(pipemesh_venv) $python3 trial_v0.py```

**Comment by chandukec** [comment]
Thanks a ton for your help, tried the same way, but still, it's giving the same exact error:
```
free(): invalid pointer
Aborted (core dumped)
```

**Comment by chandukec** [comment]
Also, while installing pipemesh scipy using: `(pipemesh_venv) $python3 -m pip install pipemesh scipy` I assume it is installed correctly, since give this message: 

```
(pipemesh_venv) csp@csp:~/Downloads/pipemesh-master$ python3 -m pip install pipemesh scipy
Collecting pipemesh
  Using cached pipemesh-1.0-py3-none-any.whl (1.1 MB)
Collecting scipy
  Using cached scipy-1.8.1-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (41.6 MB)
Collecting numpy<1.25.0,>=1.17.3
  Using cached numpy-1.22.4-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (16.9 MB)
Installing collected packages: pipemesh, numpy, scipy
Successfully installed numpy-1.22.4 pipemesh-1.0 scipy-1.8.1
```

**Comment by Duncan-Hunter** [comment]
Yes that should be correct - it might be worth it just learning GMSH in that case. They have some good documentation and good examples:

https://gmsh.info/doc/texinfo/gmsh.html

https://gmsh.info/doc/texinfo/gmsh.html#Gmsh-API

https://gitlab.onelab.info/gmsh/gmsh/-/tree/gmsh_4_10_3/examples/api

**Comment by Duncan-Hunter** [comment]
Once you have a few of the examples working, feel free to lift as much of my code as you want

**Comment by chandukec** [comment]
Many thanks for your prompt help and cooperation. Unfortunately, I am getting the same error, not sure what needs to be done, since I guess the installation is not been able to import the `pipemesh `utility correctly. As I had written in the previous post that a single line of code is not been executed correctly:

`from pipemesh import pipes`

Maybe the issue of the Ubuntu version, what do you suggest, is there any way to debug the different software that the utility wants and with the newest version of Ubuntu, it had been changed/modified, etc? As of now, I am not sure what and how to proceed further. Meanwhile, I am really grateful for your help and support.

**Comment by chandukec** [comment]
Meanwhile, after installing/sourcing the Gmsh 4.10.3 version, there is some update, but not yet successful, it is throwing the following error:

```
Error   : Gmsh has not been initialized
Error   : Gmsh has not been initialized
Error   : Gmsh has not been initialized
Error   : Gmsh has not been initialized
Error   : Gmsh has not been initialized
Error   : Gmsh has not been initialized
Traceback (most recent call last):
  File "pipe_trial.py", line 16, in <module>
    piece = pieces.TJunction(0.5, 0.3, [1, 0,0], [-2,1, 0], 0.1)
  File "/home/csp/venvs/pipemesh_venv/lib/python3.8/site-packages/pipemesh/pieces.py", line 531, in __init__
    vol_tag = vol_tags[0]
IndexError: list index out of range
```

**Comment by Duncan-Hunter** [comment]
Another simple example might work with that version of the GMSH API, this has `gmsh.initialize()`:
```python
from pipemesh import pieces, gmsh
import os
import numpy as np

model = gmsh.model
factory = model.occ
mesh = model.mesh

gmsh.initialize()
gmsh.option.setNumber("Mesh.CharacteristicLengthMax", 0.1)
"""Piece classes"""

piece = pieces.TJunction(0.5, 0.3, [1, 0,0], [-2,1, 0], 0.1)

mesh.generate(3)
gmsh.fltk.run()
gmsh.finalize()
```

**Comment by chandukec** [comment]
Thanks a lot, it's not giving errors, but neither displaying nor producing anything. It's just opening a blank gmsh window.

**Comment by Duncan-Hunter** [comment]
Can you try adding something like
```python
print(mesh.getNodes())
```
before `mesh.generate(3)`
and see what the output is

**Comment by Duncan-Hunter** [comment]
If you're using GMSH 4.10, then you might also have to replace gmsh.py in the site-packages folder

**Comment by chandukec** [comment]
Thanks a lot, I tried your inputs, by adding the lines + changing the gmsh.py files + libgmsh files. Now I am getting the following errors:

```
Traceback (most recent call last):
  File "pipe_trial.py", line 13, in <module>
    piece = pieces.TJunction(0.5, 0.3, [1, 0,0], [-2,1, 0], 0.1)
  File "/home/csp/venvs/pipemesh_venv/lib/python3.8/site-packages/pipemesh/pieces.py", line 530, in __init__
    vol_tags = FACTORY.fuse([in_tag], [mid_tag, out_tag])[0]
  File "/home/csp/venvs/pipemesh_venv/lib/python3.8/site-packages/pipemesh/gmsh.py", line 6420, in fuse
    raise Exception(logger.getLastError())
Exception: OpenCASCADE exception BRep_Tool:: TopoDS_Vertex hasn't gp_Pnt
```

**Comment by chandukec** [comment]
Meanwhile, I also added the line `gmsh.initialize()` in your recent code, since it was throwing an error stating that `Error   : Gmsh has not been initialized`, so by looking at some given examples I tried to avoid that error. But again this error: 

```
Traceback (most recent call last):
  File "pipe_trial.py", line 13, in <module>
    piece = pieces.TJunction(0.5, 0.3, [1, 0,0], [-2,1, 0], 0.1)
  File "/home/csp/venvs/pipemesh_venv/lib/python3.8/site-packages/pipemesh/pieces.py", line 530, in __init__
    vol_tags = FACTORY.fuse([in_tag], [mid_tag, out_tag])[0]
  File "/home/csp/venvs/pipemesh_venv/lib/python3.8/site-packages/pipemesh/gmsh.py", line 6420, in fuse
    raise Exception(logger.getLastError())
Exception: OpenCASCADE exception BRep_Tool:: TopoDS_Vertex hasn't gp_Pnt
```
Meanwhile, I just wanted to create a mesh (including the boundary condition) of this "Y joint" and then import that into OpenFOAM, and wanted to change the dia+length etc, I guess that is doable by this utility ?

**Comment by Duncan-Hunter** [comment]
Ok so it looks like the fusing isn't working, lets try a simple example where it doesn't need a fuse (just a simple cylinder):

```python
from pipemesh import pieces, gmsh
import os
import numpy as np

model = gmsh.model
factory = model.occ
mesh = model.mesh

gmsh.initialize()
gmsh.option.setNumber("Mesh.CharacteristicLengthMax", 0.1)

piece = pieces.Cylinder(1, 0.5, [0,0,1], 0.1)

mesh.generate(3)
gmsh.fltk.run()
gmsh.finalize()
```

**Comment by chandukec** [comment]
Thanks a lot for your prompt reply, but again there is an error, which says:

```
Error   : Unknown OpenCASCADE entity of dimension 2 with tag -3
Traceback (most recent call last):
  File "cylinder.py", line 12, in <module>
    piece = pieces.Cylinder(1, 0.5, [0,0,1], 0.1)
  File "/home/csp/venvs/pipemesh_venv/lib/python3.8/site-packages/pipemesh/pieces.py", line 236, in __init__
    super(Cylinder, self).__init__(radius, vol_tag, in_tag, out_tag,
  File "/home/csp/venvs/pipemesh_venv/lib/python3.8/site-packages/pipemesh/pieces.py", line 176, in __init__
    in_centre = np.array(FACTORY.getCenterOfMass(*in_tag))
  File "/home/csp/venvs/pipemesh_venv/lib/python3.8/site-packages/pipemesh/gmsh.py", line 6998, in getCenterOfMass
    raise Exception(logger.getLastError())
Exception: Unknown OpenCASCADE entity of dimension 2 with tag -3
```

**Comment by Duncan-Hunter** [comment]
Ok - I've recreated that error - I'm pretty sure my code won't work with that version of GMSH.

Can I check further things:
That you downloaded GMSH from: http://gmsh.info/bin/Linux/gmsh-4.3.0-Linux64-sdk.tgz

If not, one last attempt is to download from that, extract, copy `gmsh.py`, `libgmsh.so`, `libgmsh.so.4.3`, `libgmsh.so.4.3.0` to site packages as above, selecting replace if there's a conflict. Then try running the command above.

**Comment by chandukec** [comment]
Hello, good morning, sorry for the delayed response, and many thanks for your consistent help. I tried to download the files from your link and replaced the files, but again it shows an error:

```
free(): invalid pointer
Aborted (core dumped)


```

**Comment by Duncan-Hunter** [comment]
I haven't got any clear ideas then on what the issue is. Apologies
